const fs = require('fs')
const path = require('path')

const root = (...args) => path.resolve(__dirname, '..', ...args)

const jsconfigPath = root('jsconfig.json')

const createJsconfigAliases = (rootDir, items) => {
    return Object.keys(items).reduce((acc, it) => ({
        ...acc,
        [it]: [path.join(rootDir, path.basename(items[it]))],
    }), {})
}

const mergeAliases = (acc, [aliasRoot, aliases]) => ({
    ...acc,
    ...createJsconfigAliases(aliasRoot, aliases),
})

export const writeJsconfig = (...args) => {
    
    const jsconfigAliases = args.reduce(mergeAliases, {})
    
    const jsconfigData = JSON.stringify({
        description: 'DO NOT EDIT. THIS FILE IS GENERATED BY config/aliases.js.',
        compilerOptions: {
            baseUrl: 'src',
            paths: jsconfigAliases,
        },
    }, null, 4)
    
    fs.writeFileSync(jsconfigPath, jsconfigData, 'utf8')
    
}
